# Generated by Django 5.0.3 on 2024-05-23 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loop',
            name='count_bike',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='loop',
            name='count_car',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='loop',
            name='count_truck',
            field=models.IntegerField(default=0),
        ),
    ]
